export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const UPDATE_USER = "UPDATE_USER";
export const START_PENDING = "START_PENDING";
export const STOP_PENDING = "STOP_PENDING";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_MATERIAL_TYPES = "ADD_MATERIAL_TYPES";
export const ADD_COLORS = "ADD_COLORS";
export const ADD_TAGS = "ADD_TAGS";

export const SELECT_MATERIAL_TYPE = "SELECT_MATERIAL_TYPE";
export const SELECT_COLOR = "SELECT_COLOR";
export const SELECT_TAG = "SELECT_TAG";

export const SET_ALL_FILTERS = "SET_ALL_FILTERS";
export const RESET_ALL_FILTERS = "RESET_ALL_FILTERS";

export const IS_IN_FAVORITES_MODE = "IS_IN_FAVORITES_MODE";
export const INIT_FAVORITES = "INIT_FAVORITES";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

export const INIT_SAVE_PRESETS = "INIT_SAVE_PRESETS";
export const ADD_SAVE_PRESET = "ADD_SAVE_PRESET";
export const REMOVE_SAVE_PRESET = "REMOVE_SAVE_PRESET";
export const SET_PRESET_ID = "SET_PRESET_ID";

export const ADD_VR_SCANS = "ADD_VR_SCANS";
export const RESET_VR_SCANS = "RESET_VR_SCANS";

export const SET_PAGE = "SET_PAGE";
export const LOAD_MORE_ENABLE = "LOAD_MORE_ENABLE";
export const LOAD_MORE_DISABLE = "LOAD_MORE_DISABLE";

export const IS_HOME_LOADED = "IS_HOME_LOADED";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const IS_VRSCANS_LOADED = "IS_VRSCANS_LOADED";
