export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FETCH_MATERIAL_TYPES = "FETCH_MATERIAL_TYPES";
export const FETCH_COLORS = "FETCH_COLORS";
export const FETCH_TAGS = "FETCH_TAGS";

export const SELECT_MATERIAL_TYPE = "SELECT_MATERIAL_TYPE";
export const SELECT_COLOR = "SELECT_COLOR";
export const SELECT_TAG = "SELECT_TAG";
